name: printer_plus
description: Multi Printer package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: 3.7.0

dependencies:
  blue_thermal_printer:
    git:
      url: https://github.com/stepsharpdigital/blue_thermal_printer.git
      ref: dev
  easy_logger: ^0.0.2
  esc_pos_utils_plus: ^2.0.2
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.20.4
  flutter_usb_printer:
    git:
      url: https://github.com/stepsharpdigital/flutter_usb_printer.git
  network_info_plus: ^4.0.2
  printing: ^5.13.2
  win32: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0
